name: Vercel Preview Deployment

# Workflow temporarily disabled until Vercel project is set up
# Uncomment the following section after setting up Vercel integration
on:
#   pull_request:
#     branches: [ main ]
    workflow_dispatch:
        
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Deploy to Vercel for Preview
        uses: amondnet/vercel-action@v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          github-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Add Preview URL to PR
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `✅ Preview deployed to: ${{ steps.vercel-deploy.outputs.preview-url }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            }); 