name: Vercel Preview Deployment

on:
  pull_request:
    branches: [ main ]
        
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Use the official Vercel action instead
      - name: Deploy to Vercel
        uses: vercel/actions/cli@master
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--scope me'
      
      # Comment on PR with deployment URL (optional)
      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { VERCEL_DEPLOYMENT_URL } = process.env;
            if (VERCEL_DEPLOYMENT_URL) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `✅ Preview deployed to: ${VERCEL_DEPLOYMENT_URL}`
              });
            }
        env:
          VERCEL_DEPLOYMENT_URL: ${{ steps.vercel-deploy.outputs.preview-url || env.VERCEL_URL }} 